version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:8.3.0
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf  # Logstash pipeline config
      - ./logs:/usr/share/logstash/data/logfile  # Logs directory
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044"
      - "9600:9600"
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:8.3.0
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - elk

  flask:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/usr/share/logstash/data/logfile
    depends_on:
      - elasticsearch
      - logstash
    networks:
      - elk

volumes:
  es-data:
    driver: local

networks:
  elk:
    driver: bridge
