services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.0
    environment:
      - discovery.type=single-node             # Single-node cluster setup
      - cluster.name=docker-cluster            # Name of the Elasticsearch cluster
      - bootstrap.memory_lock=true             # Prevents Elasticsearch from swapping memory
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"           # Sets heap memory to 4GB
      - xpack.security.enabled=false           # Disables X-Pack security for simplicity
    ulimits:
      memlock:
        soft: -1                               # Unlimited memory lock (soft limit)
        hard: -1                               # Unlimited memory lock (hard limit)
    ports:
      - "9200:9200"                            # Maps Elasticsearch to port 9200 on the host
    volumes:
      - es-data:/usr/share/elasticsearch/data  # Persistent volume for data storage
    deploy:
      resources:
        limits:
          cpus: "5"                            # Limit to 5 CPU cores
          memory: "8g"                         # Limit memory usage to 8GB
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:8.3.0
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf  # Logstash pipeline configuration
    depends_on:
      - elasticsearch                         # Logstash starts after Elasticsearch
    deploy:
      resources:
        limits:
          cpus: "5"                           # Limit to 5 CPU cores
          memory: "8g"                        # Limit memory usage to 8GB
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:8.3.0
    ports:
      - "5601:5601"                           # Maps Kibana to port 5601 on the host
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200  # Connect Kibana to Elasticsearch
    depends_on:
      - elasticsearch                         # Kibana starts after Elasticsearch
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml  # Custom Kibana configuration
    deploy:
      resources:
        limits:
          cpus: "5"                           # Limit to 5 CPU cores
          memory: "8g"                        # Limit memory usage to 8GB
    networks:
      - elk

  flask:
    build: ./                    # Dossier contenant le Dockerfile pour Flask
    ports:
      - "5000:5000"                           # Maps Flask to port 5000 on the host
    depends_on:
      - elasticsearch                          # Flask starts after Elasticsearch
    networks:
      - elk

volumes:
  es-data:
    driver: local                             # Local volume for Elasticsearch data persistence

networks:
  elk:
    driver: bridge                            # Bridge network for container communication